####################################################
#                                                  #
#                  Basic Settings                  #
#                                                  #
####################################################

###  Global configuration  ###
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level)
  elevation: !secret elevation
  # 'metric' for Metric, 'imperial' for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  # Packages
  packages: !include_dir_named packages

config:
conversation:
map:
updater:
python_script:
sun:
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
frontend:
  javascript_version: latest
  themes: !include themes.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_cert_new
  ssl_key: !secret http_ssl_key_new
  base_url: !secret http_base_url
  trusted_networks:
    - 192.168.1.0/24
    - 127.0.0.1
    - ::1
  ip_ban_enabled: True
  login_attempts_threshold: 5

duckdns:
  domain: !secret duck_domain
  access_token: !secret duck_token

# Discover some devices automatically
# discovery:
# configurator:

tts:
  - platform: google
    time_memory: 57000

influxdb:
  host: 127.0.0.1

ifttt:
  key: !secret iftt_key

google:
  client_id: !secret g_cal_id
  client_secret: !secret g_cal_secret

ios:

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

