################################################################
## Packages / Docker-mon and monitoring containers
################################################################

homeassistant:
  customize:
    switch.grafana:
      icon: mdi:chart-line-variant
    switch.influxdb:
      icon: mdi:calculator


group:
  docker_containers:
    name: Docker Containers + NUC Processes
    control: hidden
    entities:
      # - sensor.docker_state
      - switch.grafana
      - switch.influxdb
      - sensor.mosquitto_state
      - sensor.sshd_state


sensor:
  ### System Processes ###
  - platform: template
    sensors:
      mosquitto_state:
        friendly_name: "Mosquitto"
        value_template: >-
          {% if is_state('sensor.process_mosquitto', 'on') %}
            Running
          {% else %}
            Disabled
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.process_mosquitto', 'on') %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}

  - platform: template
    sensors:
      sshd_state:
        friendly_name: "SSHD"
        value_template: >-
          {% if is_state('sensor.process_sshd', 'on') %}
            Running
          {% else %}
            Disabled
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.process_sshd', 'on') %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}

  - platform: template
    sensors:
      docker_state:
        friendly_name: "Docker"
        value_template: >-
          {% if is_state('sensor.process_docker', 'on') %}
            Running
          {% else %}
            Disabled
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.process_docker', 'on') %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}


switch:
  - platform: rest
    resource: !secret docker_grafana
    name: Grafana
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'

  - platform: rest
    resource: !secret docker_influxdb
    name: InfluxDB
    body_on: '{"state": "start"}'
    body_off: '{"state": "stop"}'
    is_on_template: '{{ value_json is not none and value_json.state == "running" }}'


automation:
  - alias: Alert when a critical container goes offline
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.grafana, switch.influxdb
        to: 'off'
        for:
          minutes: 5
    condition:
      condition: and
      conditions:
        # Only send this once per hour
        - condition: template
          value_template: >
            {% if states.automation.alert_when_a_critical_container_goes_offline.last_triggered is not none %}
              {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.alert_when_a_critical_container_goes_offline.attributes.last_triggered) | int > 3600 %} true {% else %} false
              {% endif %}
            {% else %}
            false
            {% endif %}
    action:
      - service: notify.taylor
        data_template:
          message: 'Docker container for {{ trigger.to_state.name }} is not running. Please check the status of this container as some features may stop functioning.'
          title: Container Alert
      - service: persistent_notification.create
        data_template:
          notification_id: offline_container
          title: Container Offline
          message: >
            Docker container for {{ trigger.to_state.name }} is not running. Please check the status of this container as some features may stop functioning.

  # - alias: Stop Plex Media Server at night
  #   trigger:
  #     - platform: time
  #       at: '00:00:00'
  #     - platform: state
  #       entity_id: remote.living_room
  #       to: 'off'
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: switch.plex_container
  #         state: 'on'
  #       - condition: state
  #         entity_id: remote.living_room
  #         state: 'off'
  #       - condition: time
  #         before: '06:00:00'
  #   action:
  #     - service: homeassistant.turn_off
  #       entity_id: switch.plex_container