################################################################
## Package / Homebridge
################################################################

################################################
## Customize
################################################

homeassistant:
  customize_domain:
    alarm_control_panel:
      homebridge_hidden: true

    binary_sensor:
      homebridge_hidden: true

    climate:
      homebridge_hidden: true

    cover:
      homebridge_hidden: true

    device_tracker:
      homebridge_hidden: false

    fan:
      homebridge_hidden: true

    group:
      homebridge_hidden: true

    input_boolean:
      homebridge_hidden: false

    light:
      homebridge_hidden: true

    lock:
      homebridge_hidden: true

    media_player:
      homebridge_hidden: true

    scene:
      homebridge_hidden: true

    remote:
      homebridge_hidden: true

    sensor:
      homebridge_hidden: true

    switch:
      homebridge_hidden: true
