################################################################
## Packages / Daytime Nap (30 minutes)
################################################################
homeassistant:
  customize:
    script.nap:
      google_assistant: true
      google_assistant_name: "Nap"
      friendly_name: Nap
      icon: mdi:sleep

script:
  nap:
    sequence:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sleep
    - service: light.turn_off
      entity_id: light.bedroom
    - service: climate.set_temperature
      data:
        entity_id: climate.entryway
        operation_mode: Auto
        target_temp_high: 74
        target_temp_low: 69
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_mini
        volume_level: '0.20'
    - service: tts.google_say
      data_template:
        entity_id: media_player.bedroom_mini
        message: "Alarm set for half hour"
    - delay: 00:30:00
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_mini
        volume_level: '0.40'
    - service: tts.google_say
      data_template:
        entity_id: media_player.bedroom_mini
        message: "It is time to wake up!"
    - delay: 00:0:30
    - service: media_player.volume_set
      data:
        entity_id: media_player.bedroom_mini
        volume_level: '0.60'
    - service: tts.google_say
      data_template:
        entity_id: media_player.bedroom_mini
        message: "It is time to wake up!"