################################################################
## Packages / internet_usage
## @norien - https://github.com/Norien/Home-Assistant-Config
################################################################

homeassistant:
  customize:
    sensor.external_ip:
      friendly_name: External IP
      icon: mdi:earth
    script.update_speedtest:
      friendly_name: Update Speedtest
      icon: mdi:speedometer
    sensor.ipv4_address_eno1:
      friendly_name: IPv4 Address
      icon: mdi:server-network
    sensor.ipv6_address_eno1:
      friendly_name: IPv6 Address
      icon: mdi:server-network
    sensor.received_eno1:
      friendly_name: Data Received
      icon: mdi:download-network
    sensor.sent_eno1:
      friendly_name: Data Sent
      icon: mdi:upload-network


###### STATE CARD
group:
  network:
    name: Network
    entities:
      # - sensor.hassuptime
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - script.update_speedtest
      - sensor.ipv4_address_eno1
      - sensor.ipv6_address_eno1
      - sensor.external_ip
      - sensor.packets_received_eno1
      - sensor.packets_sent_eno1
      - sensor.received_eno1
      - sensor.sent_eno1
      

sensor:
###### EXTERNAL IP FOR NOTIFY
  - platform: rest
    resource: https://api.ipify.org/?format=json
    #resource: http://ip.jsontest.com
    name: external_ip
    value_template: '{{ value_json.ip }}'
    scan_interval: 14400
###### SPEEDTEST
  - platform: speedtest
    minute:
      - 0
      - 15
    monitored_conditions:
      - ping
      - download
      - upload
    server_id: 15780
###### TIME & DATE
  - platform: time_date
    display_options:
      - 'time_date'
###### UPTIME
  - platform: uptime
    unit_of_measurement: minutes


script:
  update_speedtest:
    sequence:
      - service: sensor.update_speedtest