################################################################
## Packages / Notifications
### Target Device Automation
#   data:
#     target: device/iphone
#     target: device/desktop
################################################################


notify:
  # - name: Chrome Push
  #   platform: html5
  #   gcm_api_key: !secret html5_key
  #   gcm_sender_id: !secret html5_id
    
  - platform: pushbullet
    name: taylor
    api_key: !secret pushb_key

  # - platform: pushbullet
  #   name: marisa
  #   api_key: 


automation:
###### NOTIFY IF IP CHANGES
  - alias: Notify Of New External IP
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.taylor
        data_template:
          message: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"

# Announce new devices on the network. Thanks 2 @robotsandcakes
  - alias: "Notify if New device connected"
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.taylor
        data_template:
          message: >
            New entity ID {{ trigger.event.data.entity_id }} and hostname {{ trigger.event.data.host_name }}
