################################################################
## Packages / Presence
################################################################
homeassistant:
  customize:
    # GOOGLE TRAVEL TIME SENSORS
    sensor.marisa_phone_to_home:
      friendly_name: 'Marisa Phone to Home'
      icon: mdi:car
    script.icloud_snapshot_m:
      friendly_name: 'Update Location'
      icon: mdi:cloud-upload
    script.icloud_snapshot_t:
      friendly_name: 'Update Location'
      icon: mdi:cloud-upload
    script.arrive_home_at_night:
      friendly_name: 'Night Arrival'
      icon: mdi:weather-sunset-down 
    script.icloud_reset_interval_t:
      friendly_name: 'Scan Interval 30'
      icon: mdi:cloud-sync 
    script.icloud_reset_interval_m:
      friendly_name: 'Scan Interval 30'
      icon: mdi:cloud-sync
    script.t_scan_interval_2:
      friendly_name: 'Scan Interval 2'
      icon: mdi:cloud-sync
    script.m_scan_interval_2:
      friendly_name: 'Scan Interval 2'
      icon: mdi:cloud-sync
    sensor.scan_interval_m:
      friendly_name: 'Current Interval'
      icon: mdi:exclamation
    sensor.scan_interval_t:
      friendly_name: 'Current Interval'
      icon: mdi:exclamation

###### STATE CARD
group:
  presence:
    control: hidden
    name: Presence/Modes
    entities:
      - group.taylor
      - group.marisa
      - input_boolean.guest
      - input_boolean.away
      - input_boolean.sleep
      - sensor.holiday
  taylor:
    name: Taylor
    icon: mdi:human
    entities:
      - input_boolean.taylor
      - device_tracker.taylor_bt_rpi3
      - device_tracker.taylorsiphone
      - script.icloud_snapshot_t
      - sensor.scan_interval_t
      - script.icloud_reset_interval_t
      - script.t_scan_interval_2
  marisa:
    name: Marisa
    icon: mdi:human-female
    entities:
      - input_boolean.marisa
      - device_tracker.marisa_bt_rpi3
      - device_tracker.marisasiphone
      - sensor.marisa_phone_to_home
      - script.icloud_snapshot_m
      - sensor.scan_interval_m
      - script.icloud_reset_interval_m
      - script.m_scan_interval_2
  taylor_presence:
    name: Taylor's Presence
    icon: mdi:cellphone-iphone
    entities:
      - device_tracker.taylor_bt_rpi3
      - device_tracker.taylorsiphone
      - device_tracker.taylorsapple_watch
  marisa_presence:
    name: Marisa's Presence
    icon: mdi:cellphone-iphone
    entities:
      - device_tracker.marisa_bt_rpi3
      - device_tracker.marisasiphone


automation:
  - alias: house_mode_away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.taylor, group.marisa, input_boolean.guest
    action:
      - service_template: >
          {% if states.group.taylor.state == 'off' and states.group.marisa.state == 'off' and states.input_boolean.guest.state == 'off' and states.input_boolean.away.state == 'off' %} homeassistant.turn_on
          {% elif states.group.taylor.state == 'on' or states.group.marisa.state == 'on' or states.input_boolean.guest.state == 'on' and states.input_boolean.away.state == 'on' %} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.away
      - service_template: >
          {% if states.input_boolean.away.state == 'on' %} script.house_mode_away
          {% endif %}
      - service_template: >
            {% if (as_timestamp(now()) - as_timestamp(states.input_boolean.away.last_changed)) < 60 %} notify.ios_taylors_iphone
            {% endif %}
        data_template:
          message: >
           {% if states.input_boolean.away.state == 'off' and states.input_boolean.guest.state == 'off' %} Alarm Deactivated, Welcome Home
           {% elif states.input_boolean.away.state == 'on' and states.input_boolean.guest.state == 'off' %} Nobody Home, Alarm Activated
           {% endif %}

  - alias: house_mode_user_taylor
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3
        to: 'not_home'
        # for:
        #   minutes: 3
      - platform: state
        entity_id: device_tracker.taylorsiphone
    action:
      - service_template: >
          {% if states.device_tracker.taylorsiphone.state == 'home' or states.device_tracker.taylor_bt_rpi3.state == 'home' and states.input_boolean.taylor.state == 'off' %} homeassistant.turn_on
          {% elif states.device_tracker.taylorsiphone.state != 'home' or states.device_tracker.taylor_bt_rpi3.state == 'home' and states.input_boolean.taylor.state == 'off' and states.device_tracker.taylorsiphone.attributes.battery | int > 7 %} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.taylor

  - alias: house_mode_user_taylor_home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone, device_tracker.taylorsiphone_2, device_tracker.taylorsiphone
        to: 'home'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.taylor_bt_rpi3
            state: 'home'
          # - condition: state
          #   entity_id: device_tracker.taylors_iphone
          #   state: 'home'
          - condition: state
            entity_id: device_tracker.taylorsiphone_2
            state: 'home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.taylor

  - alias: house_mode_user_taylor_away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone, device_tracker.taylorsiphone_2
        to: 'not_home'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.taylor_bt_rpi3
            state: 'not_home'
          # - condition: state
          #   entity_id: device_tracker.taylors_iphone
          #   state: 'not_home'
          - condition: state
            entity_id: device_tracker.taylorsiphone_2
            state: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.taylor

  - alias: house_mode_user_marisa
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3
        to: 'not_home'
        # for:
        #   minutes: 3
      - platform: state
        entity_id: device_tracker.marisasiphone
    action:
      - service_template: >
          {% if states.device_tracker.marisasiphone.state == 'home' or states.device_tracker.marisa_bt_rpi3.state == 'home' and states.input_boolean.marisa.state == 'off' %} homeassistant.turn_on
          {% elif states.device_tracker.marisasiphone.state != 'home' or states.device_tracker.marisa_bt_rpi3.state == 'home' and states.input_boolean.marisa.state == 'off' and states.device_tracker.marisasiphone.attributes.battery | int > 7%} homeassistant.turn_off
          {% endif %}
        entity_id: input_boolean.marisa

  - alias: house_mode_user_marisa_home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone_2, device_tracker.marisasiphone
        to: 'home'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.marisa_bt_rpi3
            state: 'home'
          # - condition: state
          #   entity_id: device_tracker.marisas_iphone
          #   state: 'home'
          - condition: state
            entity_id: device_tracker.marisasiphone_2
            state: 'home'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.marisa

  - alias: house_mode_user_marisa_away
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone_2
        to: 'not_home'
    condition:
      - condition: and
        conditions:
          - condition: state
            entity_id: device_tracker.marisa_bt_rpi3
            state: 'not_home'
          # - condition: state
          #   entity_id: device_tracker.marisas_iphone
          #   state: 'not_home'
          - condition: state
            entity_id: device_tracker.marisasiphone_2
            state: 'not_home'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.marisa

  ### Update iCloud Tracking ###
  ###### Marisa
  - alias: marisa_update_icloud_when_leaving
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
        to: 'not_home'
        # for:
        #     minutes: 1
    action:
      # - service: device_tracker.icloud_update
      #   data:
      #     account_name: marisas_icloud
      # - delay: '00:01:00'
      - service: device_tracker.icloud_set_interval
        data:
          account_name: marisas_icloud
          interval: 1

  - alias: marisa_update_icloud_when_gone_for_half_hour
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone
        to: 'not_home'
        for:
            minutes: 30
    action:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: marisas_icloud
          interval: 5

  - alias: marisa_update_icloud_when_gone_for_hour
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone
        to: 'not_home'
        for:
            minutes: 60
    action:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: marisas_icloud
          interval: 10

  - alias: marisa_update_icloud_when_home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone_2
        to: 'home'
    action:
      - service: script.turn_on
        entity_id: script.icloud_snapshot_m

  ###### Taylor
  - alias: taylor_update_icloud_when_leaving
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone, device_tracker.taylorsiphone, device_tracker.taylorsiphone_2
        to: 'not_home'
        # for:
        #     minutes: 1
    action:
      # - service: device_tracker.icloud_update
      #   data:
      #     account_name: taylors_icloud
      # - delay: '00:01:00'
      - service: device_tracker.icloud_set_interval
        data:
          account_name: taylors_icloud
          interval: 1

  - alias: taylor_update_icloud_when_gone_for_half_hour
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone
        to: 'not_home'
        for:
            minutes: 30
    action:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: taylors_icloud
          interval: 5

  - alias: taylor_update_icloud_when_gone_for_hour
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone
        to: 'not_home'
        for:
            minutes: 60
    action:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: taylors_icloud
          interval: 10

  - alias: taylor_update_icloud_when_home
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.taylor_bt_rpi3, device_tracker.taylors_iphone, device_tracker.tayloriphone_2
        to: 'home'
    action:
      - service: script.turn_on
        entity_id: script.icloud_snapshot_t

###### Track Phones
  - alias: Marisa is home
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.home
      event: enter
    action:
      service: notify.ios_taylors_iphone
      data:
        message: "Marisa is home"

  - alias: Marisa leaves home
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.home
      event: leave
    condition:
      condition: state
      entity_id: input_boolean.away
      state: 'on'
    action:
      service: notify.ios_taylors_iphone
      data:
        message: "Marisa left home"

  - alias: Marisa is at school
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.school
      event: enter
    action:
      service: notify.ios_taylors_iphone
      data:
        message: "Marisa is at school"

  - alias: Marisa leaves school
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.school
      event: leave
    action:
      - service: notify.ios_taylors_iphone
        data:
          message: "Marisa left school"
      - service: script.turn_on
        entity_id: script.m_scan_interval_2
      
  - alias: Marisa is at nemours
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.nemours
      event: enter
    action:
      service: notify.ios_taylors_iphone
      data:
        message: "Marisa is at Nemour's"

  - alias: Marisa leaves nemours
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.nemours
      event: leave
    action:
      - service: notify.ios_taylors_iphone
        data:
          message: "Marisa left Nemour's"
      - service: script.turn_on
        entity_id: script.m_scan_interval_2

  - alias: Marisa is at knights clinic
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.knights_clinic
      event: enter
    action:
      service: notify.ios_taylors_iphone
      data:
        message: "Marisa is at KNIGHTs Clinic"

  - alias: Marisa leaves knights clinic
    trigger:
      platform: zone
      entity_id: device_tracker.marisa_bt_rpi3, device_tracker.marisas_iphone, device_tracker.marisasiphone, device_tracker.marisasiphone_2
      zone: zone.knights_clinic
      event: leave
    action:
      - service: notify.ios_taylors_iphone
        data:
          message: "Marisa left KNIGHTs Clinic"
      - service: script.turn_on
        entity_id: script.m_scan_interval_2

  ### Welcome Home ###
  - alias: 'welcome_home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'off'
    action:
      - service_template: >
          {% if states.sensor.kitchen_lux.state | float < 45 %}
          script.arrive_home_at_night
          {% endif %}
        entity_id: script.arrive_home_at_night
      - service: script.turn_on
        entity_id: script.alarm_off_script
      - service: climate.set_away_mode
        data:
          entity_id: climate.entryway
          away_mode: 'false'
      - wait_template: "{{ states.sensor.front_door_state.state == 'open' }}"
      - service: tts.google_say
        data_template:
          entity_id: media_player.family_room_home
          message: "Alarm disarmed, welcome Home"

  ### Entryway Light on when someone arrives home at night
  - alias: 'entry_way_light_night_arrival'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.taylor, input_boolean.marisa
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.entryway
          brightness: 254
          color_temp: 370


script:
  house_mode_away:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.all_except_entryway
      - service: script.turn_on
        entity_id: script.alarm_on_script
      - service: climate.set_away_mode
        data:
          entity_id: climate.entryway
          away_mode: 'true'
  
  icloud_snapshot_t:
    sequence:
      - service: device_tracker.icloud_update
        data:
          account_name: taylors_icloud

  icloud_reset_interval_t: 
    sequence:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: taylors_icloud
          interval: 30

  t_scan_interval_2: 
    sequence:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: taylors_icloud
          interval: 2

  icloud_snapshot_m:
    sequence:
      - service: device_tracker.icloud_update
        data:
          account_name: marisas_icloud 
  
  icloud_reset_interval_m:
    sequence:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: marisas_icloud
          interval: 30

  m_scan_interval_2:
    sequence:
      - service: device_tracker.icloud_set_interval
        data:
          account_name: marisas_icloud
          interval: 2

  arrive_home_at_night:
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - light.entryway
          brightness: 255
          rgb_color: [255,255,255]
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room
          brightness: 200

sensor:
###### GOOGLE TRAVEL TIME
  - platform: google_travel_time
    name: Marisa Phone To Home
    api_key: !secret travel_time_key
    origin: device_tracker.marisasiphone
    destination: zone.home

  - platform: template
    sensors:
      scan_interval_m:
        value_template: '{{ states.device_tracker.marisasiphone.attributes["interval"] | replace(" min", "") | float | int }}'
        unit_of_measurement: 'min'

  - platform: template
    sensors:
      scan_interval_t:
        value_template: '{{ states.device_tracker.taylorsiphone.attributes["interval"] | replace(" min", "") | float | int }}'
        unit_of_measurement: 'min'


###### MODES / PEOPLE
input_boolean:
  guest:
    name: Guest
    icon: mdi:account-box
    initial: off
  away:
    name: Away
    icon: mdi:account-off
    initial: off
  taylor:
    name: Taylor
    icon: mdi:account
  marisa:
    name: Marisa
    icon: mdi:account
