################################################################
## Packages / Master Bedroom
################################################################

group:
  room_bedroom:
    name: Master Bedroom
    icon: mdi:hotel
    # view: yes
    entities:
      - group.master_bedroom_lights
      - group.our_room
      - group.bedroom_mini_main
      - group.bedroom_chromecast_main
      - group.bedroom_roku_main
      - group.master_bedroom_switch

  master_bedroom_lights:
    name: Master Bedroom Lights
    icon: mdi:lightbulb-on
    entities:
      - light.bedroom
      - light.side_table

  master_bedroom_switches:
    name: Dimmer Switches
    icon: mdi:nintendo-switch
    entities:
      - sensor.bedroom_switch
      - sensor.bedroom_dimmer_switch
      - sensor.bedroom_dimmer_battery


sensor:
###### Master Bedroom Dimmer Switch ###
  - platform: rest
    resource: !secret hue_sensor_18
    value_template: '{{ value_json.state.buttonevent }}'
    scan_interval: 2
    name: 'Master Bedroom Dimmer State'
  - platform: template
    sensors:
      master_bedroom_dimmer_state:
        friendly_name: 'Master Bedroom Dimmer Last Button Push'
        value_template: >-
                      {% if states('sensor.master_bedroom_dimmer_state_2')[0] == "1" %}
                        On
                      {% elif states('sensor.master_bedroom_dimmer_state_2')[0] == "4" %}
                        Off
                      {% else %}
                        None
                      {% endif %}

  - platform: rest
    resource: !secret hue_sensor_18
    value_template: '{{ value_json.state.lastupdated }}'
    scan_interval: 10
    name: 'Master Bedroom Dimmer Last Update'

  - platform: template
    sensors:
      master_bedroom_dimmer_last_update:
        friendly_name: 'Master Bedroom Last Used'
        value_template: >-
          {{ as_timestamp(strptime(states('sensor.master_bedroom_dimmer_last_update_2')[:19], "%Y-%m-%dT%X"))|timestamp_custom("%a, %B %d")}}

  - platform: rest
    resource: !secret hue_sensor_18
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Master Bedroom Dimmer Battery'


automation:
  ### MASTER BEDROOM Motion Sensor Lights ###
###### Daytime NOT Sleeping On
  - alias: 'master_bedroom_light_on_daytime'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: 'on'
      - platform: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
    condition:
      - condition: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
      - condition: state
        entity_id: input_boolean.sleep
        state: 'off'
      - condition: state
        entity_id: binary_sensor.master_bedroom_motion
        state: 'on'
      - condition: state
        entity_id: light.master_bathroom
        state: 'off'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness: 200
      - service: light.turn_on
        data:
          entity_id: light.master_bathroom
          brightness: 200
  
###### Nighttime NOT Sleeping On
  - alias: 'master_bedroom_light_on_nighttime'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: 'on'
      - platform: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
    condition:
      - condition: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
      - condition: state
        entity_id: input_boolean.sleep
        state: 'off'
      - condition: state
        entity_id: binary_sensor.master_bedroom_motion
        state: 'on'
      - condition: state
        entity_id: light.master_bathroom
        state: 'off'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.bedroom
          brightness: 125
      - service: light.turn_on
        data:
          entity_id: light.master_bathroom
          brightness: 125

###### Daytime + Sleeping On
  - alias: 'master_bedroom_light_on_daytime_sleeping'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: 'on'
      - platform: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
    condition:
      - condition: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
      - condition: state
        entity_id: input_boolean.sleep
        state: 'on'
      - condition: state
        entity_id: binary_sensor.master_bedroom_motion
        state: 'on'
      - condition: state
        entity_id: light.master_bathroom
        state: 'off'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bathroom
          brightness: 200

###### Nighttime + Sleeping On
  - alias: 'master_bedroom_light_on_night_sleeping'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bedroom_motion
        to: 'on'
      - platform: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
    condition:
      - condition: numeric_state
        entity_id: 'sensor.master_bedroom_lux'
        below: 105
      - condition: state
        entity_id: input_boolean.sleep
        state: 'on'
      - condition: state
        entity_id: binary_sensor.master_bedroom_motion
        state: 'on'
      - condition: state
        entity_id: light.master_bathroom
        state: 'off'
      - condition: state
        entity_id: light.bedroom
        state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        data:
          entity_id: light.master_bathroom
          brightness: 125

# ###### Light off after 10 minutes
#   - alias: 'master_bedroom_light_off'
#     initial_state: 'on'
#     trigger:
#       - platform: state
#         entity_id: binary_sensor.master_bedroom_motion
#         to: 'off'
#         for:
#           hours: 0
#           minutes: 10
#           seconds: 0
#     # condition:
#     #   - condition: state
#     #     entity_id: sensor.bedroom_switch
#     #     state: '[OFF_STATE_HERE]'
#     #     for:
#     #       hours: 0
#     #       minutes: 45
#     #       seconds: 0
#     action:
#       - service: light.turn_off
#         data:
#           entity_id: light.bedroom