homeassistant:
  customize:
    #Gateway
    switch.tv:
      icon: mdi:gate
      friendly_name: TV
    #Door Sensors
    binary_sensor.door_window_sensor_158d0001e72c11:
      icon: mdi:door
      friendly_name: Front Door
    binary_sensor.door_window_sensor_158d0001e72bef:
      icon: mdi:door
      friendly_name: Garage Door
    binary_sensor.door_window_sensor_158d0002025b91:
      icon: mdi:door
      friendly_name: Patio Door
    #Buttons
    binary_sensor.switch_158d0001f3b1e6:
      icon: mdi:radiobox-marked
      friendly_name: Xiaomi Button


group:
  all_xiaomi:
    name: All Xiaomi Sensors
    entities:
      - group.xiaomi_gateway

  xiaomi_gateway:
    name: Xiaomi Gateway
    entities:
      - light.gateway_light_7811dcb23ecf
      - sensor.illumination_7811dcb23ecf

  door_sensors:
    name: Door Sensors
    entities:
      - sensor.front_door_state
      - sensor.garage_door_state
      - sensor.patio_door_state



sensor:
  - platform: template
    sensors:
      front_door_state:
        friendly_name: "Front Door State"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001e72c11', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001e72c11', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

  - platform: template
    sensors:
      garage_door_state:
        friendly_name: "Garage Door State"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001e72bef', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0001e72bef', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}

  - platform: template
    sensors:
      patio_door_state:
        friendly_name: "Patio Door State"
        value_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002025b91', 'on') %}
            open
          {% else %}
            closed
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.door_window_sensor_158d0002025b91', 'on') %}
            mdi:door-open
          {% else %}
            mdi:door-closed
          {% endif %}


automation:
  #### Xiaomi Button Morning/Night
  - alias: turn_on_goodnight_script
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001f3b1e6
          click_type: single
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001f3b1e6
          click_type: long_click_press
    condition:
      - condition: time
        after: '21:00:00'
        before: '03:30:00'
    action:
      - service: script.turn_on
        entity_id: script.good_night

  - alias: turn_on_goodmorning_script
    trigger:
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001f3b1e6
          click_type: single
      - platform: event
        event_type: click
        event_data:
          entity_id: binary_sensor.switch_158d0001f3b1e6
          click_type: long_click_press
    condition:
      - condition: time
        after: '03:30:00'
        before: '11:00:00'
    action:
      - service: script.turn_on
        entity_id: script.good_morning

  ##### Example of Button automations to be adapted
  # - alias: Let a dog bark on long press
  #   trigger:
  #     platform: event
  #     event_type: click
  #     event_data:
  #       entity_id: binary_sensor.switch_158d0001f3b1e6
  #       click_type: long_click_press
  #   action:
  #     service: xiaomi_aqara.play_ringtone
  #     data:
  #       gw_mac: xxxxxxxxxxxx
  #       ringtone_id: 8
  #       ringtone_vol: 8

  # - alias: Double Click to toggle living room lamp
  #   trigger:
  #     platform: event
  #     event_type: click
  #     event_data:
  #       entity_id: binary_sensor.switch_158d0001f3b1e6
  #       click_type: double
  #   action:
  #     service: light.toggle
  #     data:
  #       entity_id: light.living_room_lamp

  #### Door Sensors Announce Door Open Through Google Home
  - alias: front_door_open_tts
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001e72c11
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.family_room_home
          volume_level: '0.80'
      - service: tts.google_say
        data_template:
          entity_id: media_player.family_room_home
          message: "Front door open!"

  - alias: garage_door_open_tts
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0001e72bef
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.family_room_home
          volume_level: '0.80'
      - service: tts.google_say
        data_template:
          entity_id: media_player.family_room_home
          message: "Garage door open!"

  - alias: patio_door_open_tts
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0002025b91
        from: 'off'
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'off'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.family_room_home
          volume_level: '0.80'
      - service: tts.google_say
        data_template:
          entity_id: media_player.family_room_home
          message: "Patio door open!"


# scripts:
#   bodri_labhoz:
#     alias: "Bodri to leg"
#     sequence:
#       - alias: "Dock out"
#         service: vacuum.xiaomi_remote_control_start
#         data:
#           entity_id: "vacuum.bodri"
#       - delay:
#           seconds: 13
#       - alias: "Step out"
#         service: vacuum.xiaomi_remote_control_move
#         data:
#           entity_id: "vacuum.bodri"
#           velocity: "0.25"
#           duration: 2500
#       - delay:
#           seconds: 3
#       - alias: "Remote end"
#         service: vacuum.xiaomi_remote_control_stop
#         data:
#           entity_id: "vacuum.bodri"